// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/zhoukeji/Desktop/React-UI/node_modules/dumi/theme-default/builtins/Badge/index.js';
